DQN:
  episode: 2000
  batch_size: 128
  gamma: 0.999
  eps_start: 0.9
  eps_end: 0.05
  eps_decay: 2000
  target_update_episode: 20
  num_hidden: 256
  num_choice_per_dim: 7

  optimizer_lr: 1e-3
  optimizer_beta1: 0.9
  optimizer_beta2: 0.999
  optimizer_eps: 1e-8
  optimizer_weight_decay: 0

  save_path: DQN_model
  save_episode: 10

  plot_episode: 10